### ISSUE TITLE
Features needed by `std`

### ISSUE THREAD

**Issue by sunfishcode** [sunfishcode/mustang#16]
Here's a survey of `std`'s use of `libc`, here are the functions `mustang` doesn't yet implement:

 - [x] Current directories: https://github.com/bytecodealliance/rsix/pull/55 and https://github.com/sunfishcode/mustang/issues/11
 - [x] Basic networking: https://github.com/bytecodealliance/rsix/pull/61 and https://github.com/sunfishcode/mustang/pull/15
 - More networking:
   - [x] Socket options: `getsockopt`, `setsockopt`: see https://github.com/sunfishcode/mustang/issues/21
   - [ ] Ancillary data on sockets: `sendmsg`, `recvmsg`, et al
   - [x] Network address translation: `getaddrinfo`, `freeaddrinfo`, `gai_strerror`: https://github.com/sunfishcode/mustang/issues/21
 - [ ] Other things used by `std::os::unix::*` such as `ucred`.
 - [ ] Child processes
    - [x] `fork`
    - [x] `execve`
    - [ ] `posix_spawn`
    - [ ] `pipe2`
    - [ ] `setgroups`
    - [ ] `setgid`, `setuid`
 - [x] Threads: `pthread_*` and TLS. https://github.com/sunfishcode/mustang/issues/20 is one option.
 - [x] Unwinding: `_Unwind*`; see #27
 - [x] Condvar: https://github.com/sunfishcode/mustang/issues/40

It's possible there are things I missed, but this should be most of it. Most of these need support in `rustix` first. If anyone wants to work on any of these, please comment here and/or file issues and link them here so we can avoid duplicating effort!

**Comment by sunfishcode** [comment]
It appears `getaddrinfo` etc. needs `getsockopt`/`setsockopt` functionality, so I'll plan to pull that into https://github.com/sunfishcode/mustang/issues/21.

**Comment by sunfishcode** [comment]
To my knowledge, no one is actively working on this, so I'm closing this issue for now. If anyone is interested, please reach out.
